# -*- coding: utf-8 -*-
"""벤치마크 전용 합성 데이터 생성기.

`Test Data/` 의 실제 CSV 구조(ETS Datalog Converter 포맷)를 그대로 본떠 임의 규모의
Pre/Post 데이터로그를 만든다. 회귀 검증용이 아니다 (CLAUDE.md §5-4 는 회귀 검증에
합성 데이터를 쓰는 것을 금지하지만, 이 스크립트의 산출물은 성능 측정에만 쓰고 절대
tests/golden/ 스냅샷 생성에 사용하지 않는다).

실측으로 확인한 실제 포맷 (Test Data/SM3502Q/00_MVT0-0_1111_111/):
    Test Name    행 : 라벨 + 빈칸 4개 + 항목명...   (find_test_item_name_row 가
                       "Test Name" 라벨을 가진 행 중 비어있지 않은 셀이 가장 많은
                       행을 고른다 -- 로그 메타의 단일값 "Test Name" 행과 구분해야
                       하므로 둘 다 만든다)
    Test Number  행 : 라벨 + 빈칸 4개 + 항목별 시험번호
    Lower Limit  행
    Upper Limit  행
    Units        행 : 대부분 'V', DEVICE_ID 항목만 'Binnary' (실측 그대로)
    데이터 헤더    행 : Site #,Serial #,Bin,XCoord,YCoord + 항목 열은 빈칸
    데이터 행      : Site#,Serial#,Bin,XCoord,YCoord,<측정값...>

DEVICE_ID 는 별도 컬럼이 아니라 항목 컬럼 중 하나이며(ID_ITEM_NAMES, cdf_compare_tool.py),
extract_item_records_from_meta_table 가 이름으로 찾아 분석 항목에서 제외하고 Pre/Post
조인 키로만 쓴다.
"""
import argparse
import csv
import os
import random

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))

DEVICE = "PERF01"
CONDITION_FOLDER = "00_PV1-0_L001_B001"
ITEM = "HTOL"
READOUT = "1000hrs"
TEMP_CODE = "RR01"  # ft_temp_from_code: 'rr'로 시작 -> Room

LEAD_COLS = ["Site #", "Serial #", "Bin", "XCoord", "YCoord"]
FAIL_RATE = 0.03


def make_item_names(n_items, device_id_index):
    names = [f"ITEM_{i:05d}_V" for i in range(n_items)]
    names[device_id_index] = "DEVICE_ID"
    return names


def build_preamble():
    # 실제 로그의 전처리 헤더를 축약해 그대로 본뜬다. 파서는 라벨(Test Name / Test
    # Number / ...)로 행을 찾으므로 줄 번호 자체는 실제 파일과 달라도 무방하다.
    return [
        [f"             {DEVICE}_{TEMP_CODE}_AAA_R001_PERFFIXTURE.log"],
        [],
        ["Report Generated By        ", "make_perf_fixture.py"],
        ["On                         ", "synthetic"],
        ["Utility Version            ", "n/a"],
        [],
        ["Test Name                  ", f"{DEVICE}_{TEMP_CODE}_AAA_R001"],  # 로그 메타 (단일값)
        ["Family Name                ", "PerfBenchmark"],
        [],
        ["Test program               ", "n/a"],
        [],
    ]


def build_meta_rows(item_names, test_numbers, lower_limits, upper_limits, units):
    pad = ["", "", "", ""]
    return {
        "name": ["Test Name"] + pad + item_names,
        "number": ["Test Number"] + pad + test_numbers,
        "lower": ["Lower Limit"] + pad + lower_limits,
        "upper": ["Upper Limit"] + pad + upper_limits,
        "units": ["Units"] + pad + units,
        "header": LEAD_COLS + [""] * len(item_names),
    }


def generate_table(n_items, n_units, device_id_index, device_ids, rng, is_pre, serial_start):
    item_names = make_item_names(n_items, device_id_index)
    test_numbers = [f"{i // 20 + 1}.{i % 20 + 1}" for i in range(n_items)]
    lower_limits = ["-50"] * n_items
    upper_limits = ["50"] * n_items
    units = ["V"] * n_items
    lower_limits[device_id_index] = "0"
    upper_limits[device_id_index] = "99999999999"
    units[device_id_index] = "Binnary"

    meta = build_meta_rows(item_names, test_numbers, lower_limits, upper_limits, units)

    rows = []
    rows.extend(build_preamble())
    rows.append(meta["name"])
    rows.append(meta["number"])
    rows.append(meta["lower"])
    rows.append(meta["upper"])
    rows.append(meta["units"])
    rows.append(meta["header"])

    n_fail = 0 if is_pre else max(1, round(n_units * FAIL_RATE))
    fail_serials = set(rng.sample(range(n_units), n_fail)) if n_fail else set()

    for i in range(n_units):
        serial = serial_start + i if is_pre else i + 1
        bin_code = 1 if i not in fail_serials else rng.choice((2, 4, 5, 8))
        row = [1, serial, bin_code, "N/A", "N/A"]
        measured = [round(rng.gauss(0.0, 1.0), 4) for _ in range(n_items)]
        measured[device_id_index] = device_ids[i]
        row.extend(measured)
        rows.append(row)
    return rows


def write_csv(path, rows):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh)
        writer.writerows(rows)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--items", type=int, default=1000, help="항목(컬럼) 수 (DEVICE_ID 포함)")
    parser.add_argument("--units", type=int, default=3000, help="Post 유닛(행) 수. Pre 는 이 3배")
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--out", default=os.path.join(PROJECT_ROOT, "Perf Data"))
    args = parser.parse_args()

    if args.items < 2:
        raise SystemExit("--items 는 DEVICE_ID 포함 최소 2 이상이어야 합니다.")

    rng = random.Random(args.seed)
    device_id_index = args.items // 3

    post_units = args.units
    pre_units = args.units * 3

    post_device_ids = [200_000_000 + rng.randrange(0, 99_999_999) for _ in range(post_units)]
    # 겹침 보장: Pre 는 Post 의 DEVICE_ID 를 전부 포함 + 남는 자리를 새 ID 로 채운다.
    extra_needed = pre_units - post_units
    extra_ids = [300_000_000 + rng.randrange(0, 99_999_999) for _ in range(extra_needed)]
    pre_device_ids = post_device_ids + extra_ids
    rng.shuffle(pre_device_ids)

    post_rows = generate_table(
        args.items, post_units, device_id_index, post_device_ids, rng,
        is_pre=False, serial_start=1,
    )
    pre_rows = generate_table(
        args.items, pre_units, device_id_index, pre_device_ids, rng,
        is_pre=True, serial_start=100_000,
    )

    base = os.path.join(args.out, DEVICE, CONDITION_FOLDER)
    post_path = os.path.join(base, "01_Post", f"{DEVICE}_{TEMP_CODE}_AAA_{ITEM}_{READOUT}.CSV")
    pre_path = os.path.join(base, "00_Pre", f"{DEVICE}_{TEMP_CODE}_ListAll_perf.csv")

    write_csv(post_path, post_rows)
    write_csv(pre_path, pre_rows)

    print(f"Post: {post_path} ({post_units} units, {args.items} items)")
    print(f"Pre : {pre_path} ({pre_units} units, {args.items} items)")
    print(f"DEVICE_ID 겹침: Post {len(set(post_device_ids))}건 전부 Pre 에 포함")


if __name__ == "__main__":
    main()
